export class ErrorCodes {
  static Codes = Object.freeze({
    UNKNOWN: "UNKNOWN",
    NETWORK: "NETWORK",
    TIMEOUT: "TIMEOUT",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    RATE_LIMITED: "RATE_LIMITED",
    SERVER: "SERVER",
    BAD_REQUEST: "BAD_REQUEST",
    NO_LISTENER: "NO_LISTENER",
    CONTEXT_INVALIDATED: "CONTEXT_INVALIDATED",
    INVALID_ENDPOINT: "INVALID_ENDPOINT",
    INVALID_METHOD: "INVALID_METHOD",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVALID_BODY: "INVALID_BODY",
    LOGIN_FAILED: "LOGIN_FAILED",
    REGISTRATION_FAILED: "REGISTRATION_FAILED",
    NO_DATA: "NO_DATA",
    BUY_FAILED: "BUY_FAILED",
    SELL_FAILED: "SELL_FAILED",
    CALCULATION_FAILED: "CALCULATION_FAILED",
    INVALID_AMOUNT: "INVALID_AMOUNT",
    INVALID_PORTFOLIO: "INVALID_PORTFOLIO",
    STORAGE_GET_FAILED: "STORAGE_GET_FAILED",
    STORAGE_SET_FAILED: "STORAGE_SET_FAILED",
    HEALTH_CHECK_FAILED: "HEALTH_CHECK_FAILED",
    OUTDATED_VERSION: "OUTDATED_VERSION",
    WEBSOCKET_CONNECTION_FAILED: "WEBSOCKET_CONNECTION_FAILED",
    PARSE_ERROR: "PARSE_ERROR",
    INVALID_DATA: "INVALID_DATA",
    INVALID_NOTIFICATION_TYPE: "INVALID_NOTIFICATION_TYPE",
    INVALID_NOTIFICATION_MESSAGE: "INVALID_NOTIFICATION_MESSAGE",
    STORAGE_REMOVE_FAILED: "STORAGE_REMOVE_FAILED",
  });

  static UserMessages = Object.freeze({
    UNKNOWN: "Something went wrong. Please try again.",
    NETWORK: "Network error. Check your connection and try again.",
    TIMEOUT: "Request timed out. Try again.",
    UNAUTHORIZED: "Please log in again.",
    FORBIDDEN: "You don’t have permission to do that.",
    NOT_FOUND: "Not found.",
    RATE_LIMITED: "Too many requests. Try again later.",
    SERVER: "Server error. Try again later.",
    BAD_REQUEST: "Invalid request.",
    NO_LISTENER: "Page isn’t ready yet. Refresh and try again.",
    CONTEXT_INVALIDATED: "Extension reloaded/updated. Refresh the page.",
    INVALID_ENDPOINT: "Requested resource is unavailable. Try again later.",
    INVALID_METHOD: "Invalid method used for the request.",
    INVALID_TOKEN: "Session token is invalid. Please log in again.",
    INVALID_BODY: "Request body is invalid. Please contact support.",
    LOGIN_FAILED: "Login failed. Check your credentials and try again.",
    REGISTRATION_FAILED:
      "Registration failed. Check your details and try again.",
    NO_DATA: "No data received from server. Try again later.",
    BUY_FAILED: "Purchase failed. Please try again.",
    SELL_FAILED: "Sale failed. Please try again.",
    CALCULATION_FAILED: "Failed to calculate price. Please try again.",
    INVALID_AMOUNT: "Attempted amount is invalid. Please try again.",
    INVALID_PORTFOLIO: "Portfolio data is invalid. Please try again.",
    STORAGE_GET_FAILED: "Failed to retrieve data. Please try again.",
    STORAGE_SET_FAILED: "Failed to save data. Please try again.",
    HEALTH_CHECK_FAILED: "Unable to connect to server. Check your connection.",
    OUTDATED_VERSION:
      "Your extension is outdated. Please update to the latest version.",
    WEBSOCKET_CONNECTION_FAILED:
      "Failed to connect to server. Check your connection and try again.",
    PARSE_ERROR: "Received malformed data. Please try again.",
    INVALID_DATA: "Received invalid data. Please try again.",
    INVALID_NOTIFICATION_TYPE: "Invalid notification type.",
    INVALID_NOTIFICATION_MESSAGE: "Invalid notification message.",
    STORAGE_REMOVE_FAILED: "Failed to remove data. Please try again.",
  });
}
